Repository RedCollege/redcollege-nuxt-module, pull requests merged in 2024-11, with the labels that each got.

#13 FEAT(models, planificacionModule): Actualizar modelos, agregar modelo…
  src/runtime/models/Planificacion/entradaCurricular.ts
  src/runtime/models/Planificacion/itemEntradaCurricular.ts
  src/runtime/models/Planificacion/planificacion.ts
  src/runtime/repository/modules/planificaciones/planificacion.ts
Labels: requerimiento, size/M

#16 FIX(repository): Arreglar ruta para consumir asignaturas por sige id
  src/runtime/repository/modules/establecimiento/curso.ts
Labels: error, size/XS

#17 FIX(repository): Arreglar ruta para consumir asignatura con nuevos pa…
  src/runtime/repository/modules/establecimiento/curso.ts
Labels: error, size/XS

#18 FEAT(repository): Agregar ruta para relacionar items con unidades
  src/runtime/repository/modules/planificaciones/planificacion.ts
Labels: requerimiento, size/S

#19 FIX(repository): Arreglar rutas de unidades
  src/runtime/repository/modules/planificaciones/planificacion.ts
  src/runtime/repository/modules/planificaciones/unidad.ts
Labels: requerimiento, size/M

#21 7 agregar ruta relacion item unidad
  src/runtime/models/Curriculum/entrada_curricular.ts
Labels: requerimiento, size/XS

#23 9 fix tipos en auxiliar
  src/runtime/models/General/archivo.ts
  src/runtime/repository/modules/general/auxiliar.ts
Labels: error, size/S

#24 fix: Agregar segmento de ruta faltante en unidad.ts
  src/runtime/repository/modules/planificaciones/unidad.ts
Labels: error, size/XS

#25 11 agregar ruta total componentes curriculares
  src/runtime/models/Planificacion/planificacion.ts
  src/runtime/repository/modules/planificaciones/planificacion.ts
Labels: requerimiento, size/S

#20 feat(planificaciones): agregar interfaz de libro
  src/runtime/models/Establecimiento/curso.ts
  src/runtime/models/LibroDigital/index.ts
  src/runtime/models/LibroDigital/libro.ts
  src/runtime/models/Planificacion/planificacion.ts
  src/runtime/models/index.ts
Labels: size/S
