Repository RedCollege/redcollege-nuxt-module, pull requests merged in 2024-10, with the labels that each got.

#5 Seccion planificacion
  src/runtime/repository/modules/planificaciones/planificacion.ts
Labels: size/XS

#6 Params en getall de las planificaciones
  src/runtime/repository/modules/planificaciones/planificacion.ts
Labels: size/S

#7 Correcciones en las rutas de la seccion de planificacion
  src/runtime/repository/modules/planificaciones/planificacion.ts
Labels: size/S

#8 agregado toggle y toggle-group
  playground/pages/index.vue
  src/runtime/components/ui/toggle-group/ToggleGroup.vue
  src/runtime/components/ui/toggle-group/ToggleGroupItem.vue
  src/runtime/components/ui/toggle-group/index.ts
  src/runtime/components/ui/toggle/Toggle.vue
  src/runtime/components/ui/toggle/index.ts
Labels: size/L

#9 2 crear models y rutas para establecimiento
  src/runtime/models/Establecimiento/asignatura_curricular.ts
  src/runtime/models/Establecimiento/asignatura_sige.ts
  src/runtime/models/Establecimiento/curso_asignatura.ts
  src/runtime/plugins/api.ts
  src/runtime/repository/modules/establecimiento/establecimiento.ts
  src/runtime/utils/apiModuleFactory.ts
Labels: size/M

#11 Agregado metodo para obtener los cursos de un establecimiento por año
  src/runtime/repository/modules/establecimiento/establecimiento.ts
Labels: requerimiento, size/S

#10 Added route to clone planificacion
  package-lock.json
  src/runtime/models/Planificacion/itemEntradaCurricular.ts
  src/runtime/models/Planificacion/planificacion.ts
  src/runtime/models/Planificacion/unidad.ts
  src/runtime/repository/modules/planificaciones/planificacion.ts
Labels: size/M

#12 Agregar parametro isDinamico para filtrar por ese valor
  src/runtime/models/Auth/usuario.ts
  src/runtime/models/Establecimiento/curso.ts
  src/runtime/models/Establecimiento/rol.ts
  src/runtime/repository/modules/establecimiento/establecimiento.ts
Labels: size/S
