Repository RedCollege/redcollege-nuxt-module, pull requests merged in 2024-12, with the labels that each got.

#28 FEAT(unidad): Agregar items a la unidad
  src/runtime/repository/modules/planificaciones/unidad.ts
Labels: size/XS

#27 11 crear models y rutas para contenido
  src/runtime/models/Planificacion/contenido.ts
  src/runtime/repository/modules/index.ts
  src/runtime/repository/modules/planificaciones/contenido.ts
  src/runtime/repository/modules/planificaciones/contenido_actividad.ts
  src/runtime/repository/modules/planificaciones/contenido_recurso.ts
  src/runtime/utils/apiModuleFactory.ts
Labels: requerimiento, size/L

#30 FIX(models): Agregar models IContenido
  src/runtime/models/Planificacion/index.ts
Labels: size/XS

#31 feat: Agregar campo is_cumplido a la interfaz de Contenido
  src/runtime/models/Planificacion/contenido.ts
Labels: requerimiento, size/S

#32 feat: Agregar rutas y modelo para adecuaciones curriculares
  src/runtime/models/Planificacion/adecuacion_curricular.ts
  src/runtime/models/Planificacion/index.ts
  src/runtime/repository/modules/index.ts
  src/runtime/repository/modules/planificaciones/adecuacion_curricular.ts
Labels: requerimiento, size/M

#33 fix: Arreglar importacion de adecuacion curricular
  src/runtime/repository/modules/index.ts
  src/runtime/utils/apiModuleFactory.ts
Labels: error, size/L

#34 17 cambiar interfaz para crear adecuaciones curriculares
  src/runtime/models/Planificacion/adecuacion_curricular.ts
Labels: error, size/S
