Repository RedCollege/redcollege-nuxt-module, pull requests merged in 2025-01, with the labels that each got.

#35 feat: Agregar params de nombre y asignatura para filtrar
  src/runtime/repository/modules/planificaciones/adecuacion_curricular.ts
Labels: requerimiento, size/XS

#36 Agregar relacion de contenido a IAdecuacionCurricular
  src/runtime/models/Curriculum/item_entrada_curricular.ts
  src/runtime/models/Planificacion/adecuacion_curricular.ts
Labels: requerimiento, size/XS

#37 Add time picker component
  src/runtime/components/ui/time-picker/index.ts
  src/runtime/components/ui/time-picker/time-picker-input.vue
  src/runtime/components/ui/time-picker/time-picker-utils.ts
  src/runtime/components/ui/time-picker/time-picker.vue
Labels: size/L

#38 18 agregar campo adjuntos ids en modelo de mensaje
  src/runtime/models/Comunicacion/mensaje.ts
  src/runtime/repository/modules/comunicacion/adjunto.ts
Labels: requerimiento, size/M
