Repository RedCollege/redcollege-nuxt-module, pull requests merged in 2025-04, with the labels that each got.

#46 feat(planificacion): modificar interfaz de la unidad
  src/runtime/models/Planificacion/unidad.ts
Labels: size/XS

#49 FEAT(contenidoModule): Agregar ruta para duplicar un contenido
  src/runtime/repository/modules/planificaciones/contenido.ts
Labels: requerimiento, size/XS

#53 UPDATE(models-contenido): Actualizar el model de IContenido
  src/runtime/models/Planificacion/contenido.ts
Labels: requerimiento, size/S

#56 FEAT(models-planificacion-contenido): Agregar atributo a interface IC…
  playground/pages/animations.vue
  src/runtime/models/Planificacion/contenido.ts
Labels: diseño, requerimiento, size/XS

#59 Prueba 4
  playground/pages/animations.vue
Labels: size/XS

#61 prueba 6
  playground/pages/animations.vue
Labels: size/XS

#55 20 enfermeria ficha salud
  src/runtime/models/Enfermeria/configuracion_item.ts
  src/runtime/models/Enfermeria/enfermedad_discapacidad.ts
  src/runtime/models/Matricula/antecedente_salud.ts
  src/runtime/repository/modules/enfermeria/configuracion_item.ts
  src/runtime/repository/modules/enfermeria/enfermedad_discapacidad.ts
  src/runtime/repository/modules/enfermeria/registro_accidente.ts
  src/runtime/repository/modules/enfermeria/registro_atencion.ts
Labels: size/M

#52 feat(tooltip) agregar delayduration por defecto en 100
  src/runtime/components/ui/tooltip/Tooltip.vue
Labels: size/XS

#48 fix(multiselect): arreglar evento de cierre que no permite eliminar items
  package-lock.json
  package.json
  src/runtime/components/ui/multi-select/MultiSelect.vue
  test/components/MultiSelect.test.ts
  test/fixtures/basic/nuxt.config.ts
  vite.config.ts
  vitest.config.ts
Labels: size/L
