Repository RedCollege/redcollege-nuxt-module, pull requests merged in 2025-05, with the labels that each got.

#64 98 generar descargable por planificacion detallada
  src/runtime/repository/modules/planificaciones/planificacion.ts
Labels: size/XS

#63 Descargables modulo enfermeria
  src/runtime/models/Enfermeria/registro_accidente.ts
  src/runtime/models/Enfermeria/registro_atencion.ts
  src/runtime/repository/modules/enfermeria/registro_accidente.ts
  src/runtime/repository/modules/enfermeria/registro_atencion.ts
Labels: size/M

#65 53 agregar variants a progress component
  src/runtime/assets/tailwind.css
  src/runtime/components/ui/progress/index.ts
  src/runtime/models/Enfermeria/estadistica.ts
  src/runtime/models/Enfermeria/index.ts
  src/runtime/repository/modules/enfermeria/estadistica.ts
  src/runtime/repository/modules/index.ts
  src/runtime/tailwind.config.js
  src/runtime/utils/apiModuleFactory.ts
Labels: requerimiento, size/L

#68 fix: Actualizar el hsl del orange en el tailwind.css
  src/runtime/assets/tailwind.css
Labels: diseño, size/XS

#69 Parametro opcional para permitir elegir entre previsualizar y descargar archivos
  src/runtime/repository/modules/general/auxiliar.ts
Labels: requerimiento, size/M

#72 feat: Agregar prop para el componente progress
  src/runtime/components/ui/progress/Progress.vue
Labels: diseño, requerimiento, size/M

#77 FEAT: Agregar soporte de TS en el template de pug
  package-lock.json
  package.json
  playground/pages/animations.vue
  playground/tsconfig.json
  tsconfig.json
Labels: size/S

#76 feat(general): agregar props de eventos al calendar
  src/runtime/components/ui/calendar/Calendar.vue
  src/runtime/types/components/calendar.ts
Labels: size/L
